[mysql]
host = localhost
user = root
password = root
database = aniketdb
table_name = employee

# [oracle]
# host =
# user =
# password =
# service_name =

# [azure_dls]
# account_name =
# container =
# sas_token =
